#!/bin/bash
SHELL=/bin/sh
PATH=/sbin:/usr/sbin:/usr/bin:/bin
# Desenvolvido por: Mário Augusto Paglia Junior
# Paglia Host Brasil: www.pagliahost.com.br
#
# RagEditor Linux - Script para edição automatizada e interativa de emuladores de Ragnarok
# Criado em: 14/11/2017
#
# Colaboradores:
#
# Emuladores Compatíveis: brAthena, Cronus e Hércules
# Linguagens Disponíveis: Português (PT-BR)
#
# Versões:
#
# 1.0 - Desenvolvimento e criação inicial do script 

# Variáveis de Ambiente

LOCAL_EMULADOR=/home/emulador		# Mudar aqui o diretório padrão do seu emulador (até a pasta raiz)

# Menu inicial com a escolha de opções

clear
echo "###### DIGITE UMA DAS OPÇÕES ABAIXO ######"
echo ""
echo "[1] CONFIGURAR NOME DO SERVIDOR"
echo "[2] CONFIGURAR IP DA VPS (CONEXÃO)"
echo "[3] CONFIGURAR ACESSO AO BANCO DE DADOS (INTER-SERVER)"
echo "[4] CONFIGURAR PRÉ RENOVAÇÃO OU RENOVAÇÃO"
echo "[5] CONFIGURAR VERSÃO DO HEXED"
echo "[6] CONFIGURAR RATES"
echo "[7] CONFIGURAR DROPS"
echo "[8] CONFIGURAR LEVEL MÁXIMO"
echo "[9] CONFIGURAR ASPD"
echo "[10] "
echo ""
echo "PARA SAIR, DIGITE SAIR OU APERTE CTRL+C"
echo ""
echo -n ">>> Digite a opção desejada: "
read OPCAO

# Comando para descobrir qual o nome do emulador está atualmente configurado no arquivo char-server.conf

NOME_ATUAL=$(cat $LOCAL_EMULADOR/conf/char-server.conf | grep "server_name" | awk '{print $2}' |  head -n 1 || cat $LOCAL_EMULADOR/conf/char/char-server.conf | grep "server_name" | awk '{print $2}' |  head -n 1)

# Comando para descobrir qual o emulador instalado no momento, brAthena, Cronus ou Hércules

DESC_EMULADOR=$(ls -l $LOCAL_EMULADOR | awk '{print $9}' | cut -d "-" -f1 | uniq | grep -E "brAthena|Cronus|Hercules")

# CASE com as programações de cada opção

case $OPCAO in

	"1")
	
		echo ""
		echo -n ">>> Digite o nome do seu servidor: "
		read NOVO_NOME
		
		if [ "$DESC_EMULADOR" = "brAthena" ]
		then
			cat $LOCAL_EMULADOR/conf/char-server.conf | grep "server_name" | awk '{print $2}' |  head -n 1 | sed -i "s/$NOME_ATUAL/$NOVO_NOME/" $LOCAL_EMULADOR/conf/char-server.conf
			
			MOTD_BRATHENA=$(cat $LOCAL_EMULADOR/npc/MOTD.txt | grep "Bem" | cut -d '"' -f2)
			
			cat $LOCAL_EMULADOR/npc/MOTD.txt | grep "Bem" | cut -d '"' -f2 | sed -i "s/$MOTD_BRATHENA/Seja bem-vindo(a) ao $NOVO_NOME/" $LOCAL_EMULADOR/npc/MOTD.txt

			echo ""
			echo "Nome do servidor alterado com sucesso para: $NOVO_NOME"
		else
			echo ""
			echo "O nome do seu servidor não pode ser mudado, verifique se o mesmo é brAthena, Cronus ou Hércules."
		fi	
	;;		

esac	